class VerticalRotated {
  static String rotate(String char) {
    switch (char) {
      case ' ':
        return '　';
      case '↑':
        return '→';
      case '↓':
        return '←';
      case '←':
        return '↑';
      case '→':
        return '↓';
      case '。':
        return '︒';
      case '、':
        return '︑';
      case 'ー':
      case '─':
      case '-':
        return '丨';
      case '_':
        return '丨 ';
      case '−':
        return '丨';
      case '－':
        return '丨';
      case '—':
        return '丨';
      case '〜':
        return '丨';
      case '～':
        return '丨';
      case '／':
        return '＼';
      case '…':
        return '︙';
      case '‥':
        return '︰';
      case '︙':
        return '…';
      case '：':
        return '︓';
      case ':':
        return '︓';
      case '；':
        return '︔';
      case ';':
        return '︔';
      case '＝':
        return '॥';
      case '=':
        return '॥';
      case '（':
        return '︵';
      case '(':
        return '︵';
      case '）':
        return '︶';
      case ')':
        return '︶';
      case '［':
        return '﹇';
      case '[':
        return '﹇';
      case '］':
        return '﹈';
      case ']':
        return '﹈';
      case '｛':
        return '︷';
      case '{':
        return '︷';
      case '＜':
        return '︿';
      case '<':
        return '︿';
      case '＞':
        return '﹀';
      case '>':
        return '﹀';
      case '｝':
        return '︸';
      case '}':
        return '︸';
      case '「':
        return '﹁';
      case '」':
        return '﹂';
      case '『':
        return '﹃';
      case '』':
        return '﹄';
      case '【':
        return '︻';
      case '】':
        return '︼';
      case '〖':
        return '︗';
      case '〗':
        return '︘';
      case '｢':
        return '﹁';
      case '｣':
        return '﹂';
      case ',':
        return '︐';
      case '､':
        return '︑';
      default:
        return char;
    }
  }
}
